// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: test/v1/test.proto

package testv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTestPrivateTest = "/krathub.test.v1.Test/PrivateTest"
const OperationTestTest = "/krathub.test.v1.Test/Test"

type TestHTTPServer interface {
	PrivateTest(context.Context, *PrivateTestRequest) (*PrivateTestResponse, error)
	Test(context.Context, *TestRequest) (*TestResponse, error)
}

func RegisterTestHTTPServer(s *http.Server, srv TestHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/test/test", _Test_Test0_HTTP_Handler(srv))
	r.POST("/v1/test/private", _Test_PrivateTest0_HTTP_Handler(srv))
}

func _Test_Test0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTestTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Test(ctx, req.(*TestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TestResponse)
		return ctx.Result(200, reply)
	}
}

func _Test_PrivateTest0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PrivateTestRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTestPrivateTest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PrivateTest(ctx, req.(*PrivateTestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PrivateTestResponse)
		return ctx.Result(200, reply)
	}
}

type TestHTTPClient interface {
	PrivateTest(ctx context.Context, req *PrivateTestRequest, opts ...http.CallOption) (rsp *PrivateTestResponse, err error)
	Test(ctx context.Context, req *TestRequest, opts ...http.CallOption) (rsp *TestResponse, err error)
}

type TestHTTPClientImpl struct {
	cc *http.Client
}

func NewTestHTTPClient(client *http.Client) TestHTTPClient {
	return &TestHTTPClientImpl{client}
}

func (c *TestHTTPClientImpl) PrivateTest(ctx context.Context, in *PrivateTestRequest, opts ...http.CallOption) (*PrivateTestResponse, error) {
	var out PrivateTestResponse
	pattern := "/v1/test/private"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTestPrivateTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TestHTTPClientImpl) Test(ctx context.Context, in *TestRequest, opts ...http.CallOption) (*TestResponse, error) {
	var out TestResponse
	pattern := "/v1/test/test"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTestTest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
