// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/callhello/v1/hello.proto

package callhellov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义
type ErrorReason int32

const (
	// 用户未找到
	ErrorReason_USER_NOT_FOUND ErrorReason = 0
	// 用户已存在
	ErrorReason_USER_ALREADY_EXISTS ErrorReason = 1
	// 密码错误
	ErrorReason_INCORRECT_PASSWORD ErrorReason = 10
	// 错误的认证信息
	ErrorReason_INVALID_CREDENTIALS ErrorReason = 2
	// Token 类型错误
	ErrorReason_INVALID_TOKEN_TYPE ErrorReason = 3
	// Token 已过期
	ErrorReason_TOKEN_EXPIRED ErrorReason = 4
	// 没有 Token
	ErrorReason_MISSING_TOKEN ErrorReason = 5
	// Token 生成失败
	ErrorReason_TOKEN_GENERATION_FAILED ErrorReason = 6
	// 没有权限
	ErrorReason_UNAUTHORIZED ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "USER_NOT_FOUND",
		1:  "USER_ALREADY_EXISTS",
		10: "INCORRECT_PASSWORD",
		2:  "INVALID_CREDENTIALS",
		3:  "INVALID_TOKEN_TYPE",
		4:  "TOKEN_EXPIRED",
		5:  "MISSING_TOKEN",
		6:  "TOKEN_GENERATION_FAILED",
		7:  "UNAUTHORIZED",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":          0,
		"USER_ALREADY_EXISTS":     1,
		"INCORRECT_PASSWORD":      10,
		"INVALID_CREDENTIALS":     2,
		"INVALID_TOKEN_TYPE":      3,
		"TOKEN_EXPIRED":           4,
		"MISSING_TOKEN":           5,
		"TOKEN_GENERATION_FAILED": 6,
		"UNAUTHORIZED":            7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_callhello_v1_hello_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_callhello_v1_hello_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_callhello_v1_hello_proto_rawDescGZIP(), []int{0}
}

// HelloRequest 是 Hello 服务的请求消息
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *string                `protobuf:"bytes,1,opt,name=req,proto3,oneof" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_api_callhello_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_callhello_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_callhello_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetReq() string {
	if x != nil && x.Req != nil {
		return *x.Req
	}
	return ""
}

// HelloResponse 是 Hello 服务的响应消息
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rep           string                 `protobuf:"bytes,1,opt,name=rep,proto3" json:"rep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_api_callhello_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_callhello_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_api_callhello_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetRep() string {
	if x != nil {
		return x.Rep
	}
	return ""
}

var File_api_callhello_v1_hello_proto protoreflect.FileDescriptor

const file_api_callhello_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x1capi/callhello/v1/hello.proto\x12\x10krathub.hello.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x13errors/errors.proto\"-\n" +
	"\fHelloRequest\x12\x15\n" +
	"\x03req\x18\x01 \x01(\tH\x00R\x03req\x88\x01\x01B\x06\n" +
	"\x04_req\"!\n" +
	"\rHelloResponse\x12\x10\n" +
	"\x03rep\x18\x01 \x01(\tR\x03rep*\x94\x02\n" +
	"\vErrorReason\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1d\n" +
	"\x13USER_ALREADY_EXISTS\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12INCORRECT_PASSWORD\x10\n" +
	"\x1a\x04\xa8E\x91\x03\x12\x1d\n" +
	"\x13INVALID_CREDENTIALS\x10\x02\x1a\x04\xa8E\x91\x03\x12\x1c\n" +
	"\x12INVALID_TOKEN_TYPE\x10\x03\x1a\x04\xa8E\x90\x03\x12\x17\n" +
	"\rTOKEN_EXPIRED\x10\x04\x1a\x04\xa8E\x91\x03\x12\x17\n" +
	"\rMISSING_TOKEN\x10\x05\x1a\x04\xa8E\x91\x03\x12!\n" +
	"\x17TOKEN_GENERATION_FAILED\x10\x06\x1a\x04\xa8E\xf4\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\a\x1a\x04\xa8E\x93\x03\x1a\x04\xa0E\xf4\x032r\n" +
	"\tCallHello\x12e\n" +
	"\x05Hello\x12\x1e.krathub.hello.v1.HelloRequest\x1a\x1f.krathub.hello.v1.HelloResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/CallHello/HelloBd\n" +
	"\x18dev.krathub.api.hello.v1B\fHelloProtoV1P\x01Z8github.com/horonlee/krathub/api/v1/callhello;callhellov1b\x06proto3"

var (
	file_api_callhello_v1_hello_proto_rawDescOnce sync.Once
	file_api_callhello_v1_hello_proto_rawDescData []byte
)

func file_api_callhello_v1_hello_proto_rawDescGZIP() []byte {
	file_api_callhello_v1_hello_proto_rawDescOnce.Do(func() {
		file_api_callhello_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_callhello_v1_hello_proto_rawDesc), len(file_api_callhello_v1_hello_proto_rawDesc)))
	})
	return file_api_callhello_v1_hello_proto_rawDescData
}

var file_api_callhello_v1_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_callhello_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_callhello_v1_hello_proto_goTypes = []any{
	(ErrorReason)(0),      // 0: krathub.hello.v1.ErrorReason
	(*HelloRequest)(nil),  // 1: krathub.hello.v1.HelloRequest
	(*HelloResponse)(nil), // 2: krathub.hello.v1.HelloResponse
}
var file_api_callhello_v1_hello_proto_depIdxs = []int32{
	1, // 0: krathub.hello.v1.CallHello.Hello:input_type -> krathub.hello.v1.HelloRequest
	2, // 1: krathub.hello.v1.CallHello.Hello:output_type -> krathub.hello.v1.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_callhello_v1_hello_proto_init() }
func file_api_callhello_v1_hello_proto_init() {
	if File_api_callhello_v1_hello_proto != nil {
		return
	}
	file_api_callhello_v1_hello_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_callhello_v1_hello_proto_rawDesc), len(file_api_callhello_v1_hello_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_callhello_v1_hello_proto_goTypes,
		DependencyIndexes: file_api_callhello_v1_hello_proto_depIdxs,
		EnumInfos:         file_api_callhello_v1_hello_proto_enumTypes,
		MessageInfos:      file_api_callhello_v1_hello_proto_msgTypes,
	}.Build()
	File_api_callhello_v1_hello_proto = out.File
	file_api_callhello_v1_hello_proto_goTypes = nil
	file_api_callhello_v1_hello_proto_depIdxs = nil
}
