// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.32.0
// source: callhello/v1/hello.proto

package callhellov1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCallHelloHello = "/krathub.hello.v1.CallHello/Hello"

type CallHelloHTTPServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterCallHelloHTTPServer(s *http.Server, srv CallHelloHTTPServer) {
	r := s.Route("/")
	r.POST("/CallHello/Hello", _CallHello_Hello0_HTTP_Handler(srv))
}

func _CallHello_Hello0_HTTP_Handler(srv CallHelloHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCallHelloHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hello(ctx, req.(*HelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloResponse)
		return ctx.Result(200, reply)
	}
}

type CallHelloHTTPClient interface {
	Hello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloResponse, err error)
}

type CallHelloHTTPClientImpl struct {
	cc *http.Client
}

func NewCallHelloHTTPClient(client *http.Client) CallHelloHTTPClient {
	return &CallHelloHTTPClientImpl{client}
}

func (c *CallHelloHTTPClientImpl) Hello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloResponse, error) {
	var out HelloResponse
	pattern := "/CallHello/Hello"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCallHelloHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
