// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/horonlee/servora/api/gen/go/conf/v1"
	"github.com/horonlee/servora/app/sayhello/service/internal/server"
	"github.com/horonlee/servora/app/sayhello/service/internal/service"
	"github.com/horonlee/servora/pkg/bootstrap"
	"github.com/horonlee/servora/pkg/governance/registry"
	"github.com/horonlee/servora/pkg/governance/telemetry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confRegistry *conf.Registry, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	sayHelloService := service.NewSayHelloService()
	grpcServer := server.NewGRPCServer(confServer, trace, telemetryMetrics, logger, sayHelloService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer)
	return kratosApp, func() {
	}, nil
}
