// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 可复用的 TLS 配置
type TLSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`                    // 开关
	CertPath      string                 `protobuf:"bytes,2,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"` // 证书路径
	KeyPath       string                 `protobuf:"bytes,3,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`    // 私钥路径
	CaPath        string                 `protobuf:"bytes,4,opt,name=ca_path,json=caPath,proto3" json:"ca_path,omitempty"`       // CA 证书路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfig.ProtoReflect.Descriptor instead.
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *TLSConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *TLSConfig) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *TLSConfig) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *TLSConfig) GetCaPath() string {
	if x != nil {
		return x.CaPath
	}
	return ""
}

// CORS 配置
type CORS struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enable           bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`                                             // 是否启用 CORS
	AllowedOrigins   []string               `protobuf:"bytes,2,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`        // 允许的源
	AllowedMethods   []string               `protobuf:"bytes,3,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`        // 允许的方法
	AllowedHeaders   []string               `protobuf:"bytes,4,rep,name=allowed_headers,json=allowedHeaders,proto3" json:"allowed_headers,omitempty"`        // 允许的头部
	ExposedHeaders   []string               `protobuf:"bytes,5,rep,name=exposed_headers,json=exposedHeaders,proto3" json:"exposed_headers,omitempty"`        // 暴露的头部
	AllowCredentials bool                   `protobuf:"varint,6,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"` // 是否允许凭证
	MaxAge           *durationpb.Duration   `protobuf:"bytes,7,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`                                // 预检请求缓存时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CORS) Reset() {
	*x = CORS{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CORS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CORS) ProtoMessage() {}

func (x *CORS) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CORS.ProtoReflect.Descriptor instead.
func (*CORS) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *CORS) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *CORS) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *CORS) GetAllowedMethods() []string {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

func (x *CORS) GetAllowedHeaders() []string {
	if x != nil {
		return x.AllowedHeaders
	}
	return nil
}

func (x *CORS) GetExposedHeaders() []string {
	if x != nil {
		return x.ExposedHeaders
	}
	return nil
}

func (x *CORS) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *CORS) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

// Consul 配置
type ConsulConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`             // Consul 地址
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`         // 协议
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`           // 访问令牌
	Datacenter    string                 `protobuf:"bytes,4,opt,name=datacenter,proto3" json:"datacenter,omitempty"` // 数据中心
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`       // 超时时间
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`             // 服务标签
	Key           string                 `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`               // 配置键名 (仅 Config 使用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsulConfig) Reset() {
	*x = ConsulConfig{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsulConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsulConfig) ProtoMessage() {}

func (x *ConsulConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsulConfig.ProtoReflect.Descriptor instead.
func (*ConsulConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *ConsulConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ConsulConfig) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ConsulConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsulConfig) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *ConsulConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *ConsulConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConsulConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Etcd 配置
type EtcdConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"` // Etcd 端点列表
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`   // 用户名
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`   // 密码
	Timeout       *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`     // 超时时间
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`             // 配置键名 (仅 Config 使用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdConfig) Reset() {
	*x = EtcdConfig{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdConfig) ProtoMessage() {}

func (x *EtcdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdConfig.ProtoReflect.Descriptor instead.
func (*EtcdConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *EtcdConfig) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *EtcdConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EtcdConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EtcdConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *EtcdConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Nacos 配置
type NacosConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`                   // Nacos 地址
	Port          uint64                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                  // Nacos 端口
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`         // 命名空间
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`                 // 分组
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`           // 用户名
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`           // 密码
	Timeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`             // 超时时间
	DataId        string                 `protobuf:"bytes,8,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"` // 数据ID (仅 Config 使用)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NacosConfig) Reset() {
	*x = NacosConfig{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NacosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosConfig) ProtoMessage() {}

func (x *NacosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosConfig.ProtoReflect.Descriptor instead.
func (*NacosConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *NacosConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NacosConfig) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NacosConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NacosConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NacosConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NacosConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NacosConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *NacosConfig) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

// Bootstrap 配置
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`             // 应用基础配置
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`       // 服务端配置
	Client        *Client                `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`       // 客户端配置
	Data          *Data                  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`           // 数据源配置
	Registry      *Registry              `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`   // 注册中心配置
	Discovery     *Discovery             `protobuf:"bytes,6,opt,name=discovery,proto3" json:"discovery,omitempty"` // 服务发现配置
	Config        *Config                `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`       // 配置中心配置
	Trace         *Trace                 `protobuf:"bytes,8,opt,name=trace,proto3" json:"trace,omitempty"`         // 链路追踪配置
	Metrics       *Metrics               `protobuf:"bytes,9,opt,name=metrics,proto3" json:"metrics,omitempty"`     // 指标配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetDiscovery() *Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Bootstrap) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Bootstrap) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Bootstrap) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 通信服务端配置
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

// 客户端配置
type Client struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 使用 map 来管理所有下游 gRPC 服务的客户端配置
	Grpc          map[string]*Client_GRPC `protobuf:"bytes,1,rep,name=grpc,proto3" json:"grpc,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Client) GetGrpc() map[string]*Client_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

// 数据源配置
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Client        *Data_Client           `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetClient() *Data_Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// 应用配置
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           string                 `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"` // dev test prod
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Jwt           *App_Jwt               `protobuf:"bytes,4,opt,name=jwt,proto3" json:"jwt,omitempty"`                                                                                     // JWT配置
	Log           *App_Log               `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`                                                                                     // 日志配置
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *App) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *App) GetJwt() *App_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *App) GetLog() *App_Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *App) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 注册中心配置
type Registry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Registry:
	//
	//	*Registry_Consul
	//	*Registry_Etcd
	//	*Registry_Nacos
	Registry      isRegistry_Registry `protobuf_oneof:"registry"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Registry) GetRegistry() isRegistry_Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Registry) GetConsul() *ConsulConfig {
	if x != nil {
		if x, ok := x.Registry.(*Registry_Consul); ok {
			return x.Consul
		}
	}
	return nil
}

func (x *Registry) GetEtcd() *EtcdConfig {
	if x != nil {
		if x, ok := x.Registry.(*Registry_Etcd); ok {
			return x.Etcd
		}
	}
	return nil
}

func (x *Registry) GetNacos() *NacosConfig {
	if x != nil {
		if x, ok := x.Registry.(*Registry_Nacos); ok {
			return x.Nacos
		}
	}
	return nil
}

type isRegistry_Registry interface {
	isRegistry_Registry()
}

type Registry_Consul struct {
	Consul *ConsulConfig `protobuf:"bytes,1,opt,name=consul,proto3,oneof"` // Consul 配置
}

type Registry_Etcd struct {
	Etcd *EtcdConfig `protobuf:"bytes,2,opt,name=etcd,proto3,oneof"` // Etcd 配置
}

type Registry_Nacos struct {
	Nacos *NacosConfig `protobuf:"bytes,3,opt,name=nacos,proto3,oneof"` // Nacos 配置
}

func (*Registry_Consul) isRegistry_Registry() {}

func (*Registry_Etcd) isRegistry_Registry() {}

func (*Registry_Nacos) isRegistry_Registry() {}

// 服务发现配置
type Discovery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Discovery:
	//
	//	*Discovery_Consul
	//	*Discovery_Etcd
	//	*Discovery_Nacos
	Discovery     isDiscovery_Discovery `protobuf_oneof:"discovery"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery.ProtoReflect.Descriptor instead.
func (*Discovery) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Discovery) GetDiscovery() isDiscovery_Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Discovery) GetConsul() *ConsulConfig {
	if x != nil {
		if x, ok := x.Discovery.(*Discovery_Consul); ok {
			return x.Consul
		}
	}
	return nil
}

func (x *Discovery) GetEtcd() *EtcdConfig {
	if x != nil {
		if x, ok := x.Discovery.(*Discovery_Etcd); ok {
			return x.Etcd
		}
	}
	return nil
}

func (x *Discovery) GetNacos() *NacosConfig {
	if x != nil {
		if x, ok := x.Discovery.(*Discovery_Nacos); ok {
			return x.Nacos
		}
	}
	return nil
}

type isDiscovery_Discovery interface {
	isDiscovery_Discovery()
}

type Discovery_Consul struct {
	Consul *ConsulConfig `protobuf:"bytes,1,opt,name=consul,proto3,oneof"` // Consul 配置
}

type Discovery_Etcd struct {
	Etcd *EtcdConfig `protobuf:"bytes,2,opt,name=etcd,proto3,oneof"` // Etcd 配置
}

type Discovery_Nacos struct {
	Nacos *NacosConfig `protobuf:"bytes,3,opt,name=nacos,proto3,oneof"` // Nacos 配置
}

func (*Discovery_Consul) isDiscovery_Discovery() {}

func (*Discovery_Etcd) isDiscovery_Discovery() {}

func (*Discovery_Nacos) isDiscovery_Discovery() {}

// 配置中心配置
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*Config_Consul
	//	*Config_Etcd
	//	*Config_Nacos
	Config        isConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{12}
}

func (x *Config) GetConfig() isConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Config) GetConsul() *ConsulConfig {
	if x != nil {
		if x, ok := x.Config.(*Config_Consul); ok {
			return x.Consul
		}
	}
	return nil
}

func (x *Config) GetEtcd() *EtcdConfig {
	if x != nil {
		if x, ok := x.Config.(*Config_Etcd); ok {
			return x.Etcd
		}
	}
	return nil
}

func (x *Config) GetNacos() *NacosConfig {
	if x != nil {
		if x, ok := x.Config.(*Config_Nacos); ok {
			return x.Nacos
		}
	}
	return nil
}

type isConfig_Config interface {
	isConfig_Config()
}

type Config_Consul struct {
	Consul *ConsulConfig `protobuf:"bytes,1,opt,name=consul,proto3,oneof"` // Consul 配置
}

type Config_Etcd struct {
	Etcd *EtcdConfig `protobuf:"bytes,2,opt,name=etcd,proto3,oneof"` // Etcd 配置
}

type Config_Nacos struct {
	Nacos *NacosConfig `protobuf:"bytes,3,opt,name=nacos,proto3,oneof"` // Nacos 配置
}

func (*Config_Consul) isConfig_Config() {}

func (*Config_Etcd) isConfig_Config() {}

func (*Config_Nacos) isConfig_Config() {}

// 链路追踪配置
type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{13}
}

func (x *Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// Metrics 配置
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`                       // 是否开启
	MeterName     string                 `protobuf:"bytes,2,opt,name=meter_name,json=meterName,proto3" json:"meter_name,omitempty"` // Meter 名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{14}
}

func (x *Metrics) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Metrics) GetMeterName() string {
	if x != nil {
		return x.MeterName
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`   // 为 HTTP 添加 TLS 配置
	Cors          *CORS                  `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"` // CORS 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_HTTP) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Server_HTTP) GetCors() *CORS {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"` // 为 gRPC 添加 TLS 配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server_GRPC) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Client_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client_GRPC) Reset() {
	*x = Client_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_GRPC) ProtoMessage() {}

func (x *Client_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_GRPC.ProtoReflect.Descriptor instead.
func (*Client_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Client_GRPC) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Client_GRPC) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` // Redis用户名
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                 // Redis密码
	Db            int32                  `protobuf:"varint,5,opt,name=db,proto3" json:"db,omitempty"`                            // Redis数据库编号
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,7,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          []*Data_Client_GRPC    `protobuf:"bytes,1,rep,name=grpc,proto3" json:"grpc,omitempty"`
	Http          []*Data_Client_HTTP    `protobuf:"bytes,2,rep,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client) Reset() {
	*x = Data_Client{}
	mi := &file_conf_conf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client) ProtoMessage() {}

func (x *Data_Client) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client.ProtoReflect.Descriptor instead.
func (*Data_Client) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8, 2}
}

func (x *Data_Client) GetGrpc() []*Data_Client_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Data_Client) GetHttp() []*Data_Client_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Data_Client_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client_HTTP) Reset() {
	*x = Data_Client_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client_HTTP) ProtoMessage() {}

func (x *Data_Client_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client_HTTP.ProtoReflect.Descriptor instead.
func (*Data_Client_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8, 2, 0}
}

func (x *Data_Client_HTTP) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Data_Client_HTTP) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Data_Client_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Client_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Client_GRPC) Reset() {
	*x = Data_Client_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Client_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Client_GRPC) ProtoMessage() {}

func (x *Data_Client_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Client_GRPC.ProtoReflect.Descriptor instead.
func (*Data_Client_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8, 2, 1}
}

func (x *Data_Client_GRPC) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Data_Client_GRPC) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Data_Client_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type App_Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretKey     string                 `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"` // JWT密钥
	Expire        int32                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`                       // JWT过期时间，单位秒
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`                        // JWT签发者
	Audience      string                 `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Jwt) Reset() {
	*x = App_Jwt{}
	mi := &file_conf_conf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Jwt) ProtoMessage() {}

func (x *App_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Jwt.ProtoReflect.Descriptor instead.
func (*App_Jwt) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9, 0}
}

func (x *App_Jwt) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *App_Jwt) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *App_Jwt) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *App_Jwt) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type App_Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`                             // -1~5 代表了debug,info,warn,error,dpanic,panic,fatal
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                        // 日志文件名
	MaxSize       int32                  `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`          // 日志文件最大大小
	MaxBackups    int32                  `protobuf:"varint,4,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"` // 日志文件最大备份数
	MaxAge        int32                  `protobuf:"varint,5,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`             // 日志文件最大保留天数
	Compress      bool                   `protobuf:"varint,6,opt,name=compress,proto3" json:"compress,omitempty"`                       // 是否压缩日志文件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Log) Reset() {
	*x = App_Log{}
	mi := &file_conf_conf_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Log) ProtoMessage() {}

func (x *App_Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Log.ProtoReflect.Descriptor instead.
func (*App_Log) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9, 1}
}

func (x *App_Log) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *App_Log) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *App_Log) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *App_Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *App_Log) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *App_Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"t\n" +
	"\tTLSConfig\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x1b\n" +
	"\tcert_path\x18\x02 \x01(\tR\bcertPath\x12\x19\n" +
	"\bkey_path\x18\x03 \x01(\tR\akeyPath\x12\x17\n" +
	"\aca_path\x18\x04 \x01(\tR\x06caPath\"\xa3\x02\n" +
	"\x04CORS\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12'\n" +
	"\x0fallowed_origins\x18\x02 \x03(\tR\x0eallowedOrigins\x12'\n" +
	"\x0fallowed_methods\x18\x03 \x03(\tR\x0eallowedMethods\x12'\n" +
	"\x0fallowed_headers\x18\x04 \x03(\tR\x0eallowedHeaders\x12'\n" +
	"\x0fexposed_headers\x18\x05 \x03(\tR\x0eexposedHeaders\x12+\n" +
	"\x11allow_credentials\x18\x06 \x01(\bR\x10allowCredentials\x122\n" +
	"\amax_age\x18\a \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\"\xcb\x01\n" +
	"\fConsulConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x01(\tR\n" +
	"datacenter\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x10\n" +
	"\x03key\x18\a \x01(\tR\x03key\"\xa9\x01\n" +
	"\n" +
	"EtcdConfig\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\"\xef\x01\n" +
	"\vNacosConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x04R\x04port\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x17\n" +
	"\adata_id\x18\b \x01(\tR\x06dataId\"\x97\x03\n" +
	"\tBootstrap\x12!\n" +
	"\x03app\x18\x01 \x01(\v2\x0f.kratos.api.AppR\x03app\x12*\n" +
	"\x06server\x18\x02 \x01(\v2\x12.kratos.api.ServerR\x06server\x12*\n" +
	"\x06client\x18\x03 \x01(\v2\x12.kratos.api.ClientR\x06client\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.kratos.api.DataR\x04data\x120\n" +
	"\bregistry\x18\x05 \x01(\v2\x14.kratos.api.RegistryR\bregistry\x123\n" +
	"\tdiscovery\x18\x06 \x01(\v2\x15.kratos.api.DiscoveryR\tdiscovery\x12*\n" +
	"\x06config\x18\a \x01(\v2\x12.kratos.api.ConfigR\x06config\x12'\n" +
	"\x05trace\x18\b \x01(\v2\x11.kratos.api.TraceR\x05trace\x12-\n" +
	"\ametrics\x18\t \x01(\v2\x13.kratos.api.MetricsR\ametrics\"\xb2\x03\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1a\xb8\x01\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12'\n" +
	"\x03tls\x18\x04 \x01(\v2\x15.kratos.api.TLSConfigR\x03tls\x12$\n" +
	"\x04cors\x18\x05 \x01(\v2\x10.kratos.api.CORSR\x04cors\x1a\x92\x01\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12'\n" +
	"\x03tls\x18\x04 \x01(\v2\x15.kratos.api.TLSConfigR\x03tls\"\xd9\x01\n" +
	"\x06Client\x120\n" +
	"\x04grpc\x18\x01 \x03(\v2\x1c.kratos.api.Client.GrpcEntryR\x04grpc\x1aK\n" +
	"\x04GRPC\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12'\n" +
	"\x03tls\x18\x02 \x01(\v2\x15.kratos.api.TLSConfigR\x03tls\x1aP\n" +
	"\tGrpcEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.kratos.api.Client.GRPCR\x05value:\x028\x01\"\xbe\x06\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12/\n" +
	"\x06client\x18\x03 \x01(\v2\x17.kratos.api.Data.ClientR\x06client\x1a:\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x1a\xfc\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\x05R\x02db\x12<\n" +
	"\fread_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1a\xe4\x02\n" +
	"\x06Client\x120\n" +
	"\x04grpc\x18\x01 \x03(\v2\x1c.kratos.api.Data.Client.GRPCR\x04grpc\x120\n" +
	"\x04http\x18\x02 \x03(\v2\x1c.kratos.api.Data.Client.HTTPR\x04http\x1az\n" +
	"\x04HTTP\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1az\n" +
	"\x04GRPC\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xa8\x04\n" +
	"\x03App\x12\x10\n" +
	"\x03env\x18\x01 \x01(\tR\x03env\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x03jwt\x18\x04 \x01(\v2\x13.kratos.api.App.JwtR\x03jwt\x12%\n" +
	"\x03log\x18\x05 \x01(\v2\x13.kratos.api.App.LogR\x03log\x129\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1d.kratos.api.App.MetadataEntryR\bmetadata\x1ap\n" +
	"\x03Jwt\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x05R\x06expire\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x1a\xa8\x01\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x19\n" +
	"\bmax_size\x18\x03 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x04 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x05 \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\x06 \x01(\bR\bcompress\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\bRegistry\x122\n" +
	"\x06consul\x18\x01 \x01(\v2\x18.kratos.api.ConsulConfigH\x00R\x06consul\x12,\n" +
	"\x04etcd\x18\x02 \x01(\v2\x16.kratos.api.EtcdConfigH\x00R\x04etcd\x12/\n" +
	"\x05nacos\x18\x03 \x01(\v2\x17.kratos.api.NacosConfigH\x00R\x05nacosB\n" +
	"\n" +
	"\bregistry\"\xab\x01\n" +
	"\tDiscovery\x122\n" +
	"\x06consul\x18\x01 \x01(\v2\x18.kratos.api.ConsulConfigH\x00R\x06consul\x12,\n" +
	"\x04etcd\x18\x02 \x01(\v2\x16.kratos.api.EtcdConfigH\x00R\x04etcd\x12/\n" +
	"\x05nacos\x18\x03 \x01(\v2\x17.kratos.api.NacosConfigH\x00R\x05nacosB\v\n" +
	"\tdiscovery\"\xa5\x01\n" +
	"\x06Config\x122\n" +
	"\x06consul\x18\x01 \x01(\v2\x18.kratos.api.ConsulConfigH\x00R\x06consul\x12,\n" +
	"\x04etcd\x18\x02 \x01(\v2\x16.kratos.api.EtcdConfigH\x00R\x04etcd\x12/\n" +
	"\x05nacos\x18\x03 \x01(\v2\x17.kratos.api.NacosConfigH\x00R\x05nacosB\b\n" +
	"\x06config\"#\n" +
	"\x05Trace\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"@\n" +
	"\aMetrics\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x1d\n" +
	"\n" +
	"meter_name\x18\x02 \x01(\tR\tmeterNameB0Z.github.com/horonlee/krathub/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_conf_conf_proto_goTypes = []any{
	(*TLSConfig)(nil),           // 0: kratos.api.TLSConfig
	(*CORS)(nil),                // 1: kratos.api.CORS
	(*ConsulConfig)(nil),        // 2: kratos.api.ConsulConfig
	(*EtcdConfig)(nil),          // 3: kratos.api.EtcdConfig
	(*NacosConfig)(nil),         // 4: kratos.api.NacosConfig
	(*Bootstrap)(nil),           // 5: kratos.api.Bootstrap
	(*Server)(nil),              // 6: kratos.api.Server
	(*Client)(nil),              // 7: kratos.api.Client
	(*Data)(nil),                // 8: kratos.api.Data
	(*App)(nil),                 // 9: kratos.api.App
	(*Registry)(nil),            // 10: kratos.api.Registry
	(*Discovery)(nil),           // 11: kratos.api.Discovery
	(*Config)(nil),              // 12: kratos.api.Config
	(*Trace)(nil),               // 13: kratos.api.Trace
	(*Metrics)(nil),             // 14: kratos.api.Metrics
	(*Server_HTTP)(nil),         // 15: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 16: kratos.api.Server.GRPC
	(*Client_GRPC)(nil),         // 17: kratos.api.Client.GRPC
	nil,                         // 18: kratos.api.Client.GrpcEntry
	(*Data_Database)(nil),       // 19: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 20: kratos.api.Data.Redis
	(*Data_Client)(nil),         // 21: kratos.api.Data.Client
	(*Data_Client_HTTP)(nil),    // 22: kratos.api.Data.Client.HTTP
	(*Data_Client_GRPC)(nil),    // 23: kratos.api.Data.Client.GRPC
	(*App_Jwt)(nil),             // 24: kratos.api.App.Jwt
	(*App_Log)(nil),             // 25: kratos.api.App.Log
	nil,                         // 26: kratos.api.App.MetadataEntry
	(*durationpb.Duration)(nil), // 27: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	27, // 0: kratos.api.CORS.max_age:type_name -> google.protobuf.Duration
	27, // 1: kratos.api.ConsulConfig.timeout:type_name -> google.protobuf.Duration
	27, // 2: kratos.api.EtcdConfig.timeout:type_name -> google.protobuf.Duration
	27, // 3: kratos.api.NacosConfig.timeout:type_name -> google.protobuf.Duration
	9,  // 4: kratos.api.Bootstrap.app:type_name -> kratos.api.App
	6,  // 5: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	7,  // 6: kratos.api.Bootstrap.client:type_name -> kratos.api.Client
	8,  // 7: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	10, // 8: kratos.api.Bootstrap.registry:type_name -> kratos.api.Registry
	11, // 9: kratos.api.Bootstrap.discovery:type_name -> kratos.api.Discovery
	12, // 10: kratos.api.Bootstrap.config:type_name -> kratos.api.Config
	13, // 11: kratos.api.Bootstrap.trace:type_name -> kratos.api.Trace
	14, // 12: kratos.api.Bootstrap.metrics:type_name -> kratos.api.Metrics
	15, // 13: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	16, // 14: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	18, // 15: kratos.api.Client.grpc:type_name -> kratos.api.Client.GrpcEntry
	19, // 16: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	20, // 17: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	21, // 18: kratos.api.Data.client:type_name -> kratos.api.Data.Client
	24, // 19: kratos.api.App.jwt:type_name -> kratos.api.App.Jwt
	25, // 20: kratos.api.App.log:type_name -> kratos.api.App.Log
	26, // 21: kratos.api.App.metadata:type_name -> kratos.api.App.MetadataEntry
	2,  // 22: kratos.api.Registry.consul:type_name -> kratos.api.ConsulConfig
	3,  // 23: kratos.api.Registry.etcd:type_name -> kratos.api.EtcdConfig
	4,  // 24: kratos.api.Registry.nacos:type_name -> kratos.api.NacosConfig
	2,  // 25: kratos.api.Discovery.consul:type_name -> kratos.api.ConsulConfig
	3,  // 26: kratos.api.Discovery.etcd:type_name -> kratos.api.EtcdConfig
	4,  // 27: kratos.api.Discovery.nacos:type_name -> kratos.api.NacosConfig
	2,  // 28: kratos.api.Config.consul:type_name -> kratos.api.ConsulConfig
	3,  // 29: kratos.api.Config.etcd:type_name -> kratos.api.EtcdConfig
	4,  // 30: kratos.api.Config.nacos:type_name -> kratos.api.NacosConfig
	27, // 31: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	0,  // 32: kratos.api.Server.HTTP.tls:type_name -> kratos.api.TLSConfig
	1,  // 33: kratos.api.Server.HTTP.cors:type_name -> kratos.api.CORS
	27, // 34: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	0,  // 35: kratos.api.Server.GRPC.tls:type_name -> kratos.api.TLSConfig
	0,  // 36: kratos.api.Client.GRPC.tls:type_name -> kratos.api.TLSConfig
	17, // 37: kratos.api.Client.GrpcEntry.value:type_name -> kratos.api.Client.GRPC
	27, // 38: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	27, // 39: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	23, // 40: kratos.api.Data.Client.grpc:type_name -> kratos.api.Data.Client.GRPC
	22, // 41: kratos.api.Data.Client.http:type_name -> kratos.api.Data.Client.HTTP
	27, // 42: kratos.api.Data.Client.HTTP.timeout:type_name -> google.protobuf.Duration
	27, // 43: kratos.api.Data.Client.GRPC.timeout:type_name -> google.protobuf.Duration
	44, // [44:44] is the sub-list for method output_type
	44, // [44:44] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	file_conf_conf_proto_msgTypes[10].OneofWrappers = []any{
		(*Registry_Consul)(nil),
		(*Registry_Etcd)(nil),
		(*Registry_Nacos)(nil),
	}
	file_conf_conf_proto_msgTypes[11].OneofWrappers = []any{
		(*Discovery_Consul)(nil),
		(*Discovery_Etcd)(nil),
		(*Discovery_Nacos)(nil),
	}
	file_conf_conf_proto_msgTypes[12].OneofWrappers = []any{
		(*Config_Consul)(nil),
		(*Config_Etcd)(nil),
		(*Config_Nacos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
