server:
  http:
    addr: "${HADDR:0.0.0.0:8000}"
    timeout: "${HTIMEOUT:1s}"
  grpc:
    addr: "${GADDR:0.0.0.0:8001}"
    timeout: "${GTIMEHOUT:1s}"
data:
  database:
    driver: "${DB_DRIVER:mysql}"
    source: "${DB_SOURCE:krathub:krathub114514@tcp(127.0.0.1:3306)/krathub?parseTime=True&loc=Local}"
  redis:
    addr: "${RADDR:127.0.0.1:6379}"
    read_timeout: "${RREAD_TIMEOUT:0.2s}"
    write_timeout: "${RWRITE_TIMEOUT:0.2s}"
app:
  env: "${ENV:test}"
  jwt:
    secret_key: "${JWT_SECRETK_KEY:krathub_secret}"
    expire: "${JWT_EXPIRE:24}"
    issuer: "${JWT_ISSUER:krathub}"
  log:
    level: "${LOG_LEVEL:0}"  # -1debug,0info,1warn,2error,3dpanic,4panic,5fatal
    filename: "${LOG_FILENAME:krathub.log}"  # 起始于当前工作目录