server:
  http:
    addr: "${HADDR:0.0.0.0:8000}"
    timeout: "${HTIMEOUT:1s}"
  grpc:
    addr: "${GADDR:0.0.0.0:8001}"
    timeout: "${GTIMEHOUT:1s}"

data:
  database:
    driver: "${DB_DRIVER:mysql}"
    source: "${DB_SOURCE:krathub:krathub114514@tcp(127.0.0.1:3306)/krathub?parseTime=True&loc=Local}"
  redis:
    addr: "${RADDR:127.0.0.1:6379}"
    user_name: "${RUSER_NAME:}"  # Redis用户名
    password: "${RPASSWORD:redisHoron}"  # Redis密码
    db: "${RDB:5}"  # Redis数据库编号
    read_timeout: "${RREAD_TIMEOUT:0.2s}"
    write_timeout: "${RWRITE_TIMEOUT:0.2s}"
  client:
    # 这里可以配置第三方服务的客户端
    # 默认不用配置，而是在代码中直接服务发现
    grpc:
      # - service_name: hello.grpc  # nacos需要添加协议后缀
      #   endpoint: "${GRPC_ENDPOINT:127.0.0.1:8003}"
      #   enable_tls: false
      #   timeout: 5s

app:
  env: "${ENV:dev}" # dev, test, prod
  jwt:
    secret_key: "${JWT_SECRETK_KEY:krathub_secret}"
    expire: "${JWT_EXPIRE:24}"
    issuer: "${JWT_ISSUER:krathub}"
    # audience: "${JWT_AUDIENCE:krathub}"
  log:
    level: "${LOG_LEVEL:-1}"  # -1debug,0info,1warn,2error,3dpanic,4panic,5fatal
    filename: "${LOG_FILENAME:krathub.log}"  # 日志文件夹为根目录logs

# 注册中心配置
registry:
  # 使用 Consul 作为注册中心
  consul:
    addr: consul.r430.com:30080
    scheme: http
    datacenter: dc1
    timeout: 5s
  
  # 或者使用 Nacos 作为注册中心
  # nacos:
    # addr: "${NACOSR_ADDR:127.0.0.1}"
    # port: "${NACOSR_PORT:8848}"
    # namespace: "${NACOSR_NAMESPACE:public}"
    # group: "${NACOSR_GROUP:DEFAULT_GROUP}"
    # username: "${NACOSR_USERNAME:nacos}"
    # password: "${NACOSR_PASSWORD:nacos}"
    # timeout: "${NACOSR_TIMEOUT:5s}"

# 服务发现配置，一般和注册中心配置相同
discovery:
  consul:
    addr: consul.r430.com:30080
    scheme: http
    datacenter: dc1
    timeout: 5s

  # nacos:
  #   addr: "${NACOSD_ADDR:127.0.0.1}"
  #   port: "${NACOSD_PORT:8848}"
  #   namespace: "${NACOSD_NAMESPACE:public}"
  #   group: "${NACOSD_GROUP:DEFAULT_GROUP}"
  #   username: "${NACOSD_USERNAME:nacos}"
  #   password: "${NACOSD_PASSWORD:nacos}"
  #   timeout: "${NACOSD_TIMEOUT:5s}"

# 配置中心配置
config:
  # 使用 Nacos 作为配置中心
  # nacos:
  #   addr: "${NACOSC_ADDR:127.0.0.1}"
  #   port: "${NACOSC_PORT:8848}"
  #   namespace: "${NACOSC_NAMESPACE:public}"
  #   group: "${NACOSC_GROUP:DEFAULT_GROUP}"
  #   data_id: "${NACOSC_DATA_ID:krathub.yaml}"
  #   username: "${NACOSC_USERNAME:nacos}"
  #   password: "${NACOSC_PASSWORD:nacos}"
  #   timeout: "${NACOSC_TIMEOUT:5s}"

  # 使用 consul 作为配置中心
  # consul:
  #   addr: consul.r430.com:30080
  #   scheme: http
  #   datacenter: dc1
  #   timeout: 5s
  #   key: krathub/config.yaml  # 配置键名