// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Phone     *string   `gorm:"column:phone" json:"phone"`
	Avatar    *string   `gorm:"column:avatar;comment:用户头像" json:"avatar"`                     // 用户头像
	Bio       *string   `gorm:"column:bio;comment:用户简介" json:"bio"`                           // 用户简介
	Location  *string   `gorm:"column:location;comment:用户位置" json:"location"`                 // 用户位置
	Website   *string   `gorm:"column:website;comment:用户个人网站" json:"website"`                 // 用户个人网站
	Role      string    `gorm:"column:role;not null;default:user;comment:用户权限角色" json:"role"` // 用户权限角色
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:current_timestamp()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
