// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "bio", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "location", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "website", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 32, Default: "user"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
