server:
  cors:
    enable: true
app:
  env: "dev"
  metadata: {}
  jwt:
    secret_key: "krathub_default_secret_change_in_production"
    expire: "24"
    issuer: "krathub"
  log:
    level: "0"
    max_size: "20"
    max_age: "30"
    max_backups: "10"
