// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"krathub/internal/biz"
	"krathub/internal/client"
	"krathub/internal/conf"
	"krathub/internal/data"
	"krathub/internal/server"
	"krathub/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, discovery *conf.Discovery, registry *conf.Registry, confData *conf.Data, app *conf.App, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	registryDiscovery := data.NewDiscovery(discovery)
	grpcClientFactory, err := client.NewGrpcClientFactory(confData, registryDiscovery, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, confData, logger, grpcClientFactory)
	if err != nil {
		return nil, nil, err
	}
	authDBRepo := data.NewAuthDBRepo(dataData, logger)
	authGrpcRepo := data.NewAuthGrpcRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authDBRepo, authGrpcRepo, logger, app)
	authService := service.NewAuthService(authUsecase)
	userDBRepo := data.NewUserDBRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userDBRepo, logger, app, authDBRepo)
	userService := service.NewUserService(userUsecase)
	middlewareManager := server.NewMiddlewareManager(app)
	grpcServer := server.NewGRPCServer(confServer, authService, userService, middlewareManager, logger)
	httpServer := server.NewHTTPServer(confServer, authService, userService, middlewareManager, logger)
	kratosApp := newApp(logger, registrar, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
