// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/auth/v1/auth.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // 用户名
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 用户邮箱
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"` // 用户手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 邮箱注册请求
type SignupByEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 用户名最小长度5
	// 密码最小长度5，最大长度10
	Password        string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm string `protobuf:"bytes,3,opt,name=password_confirm,json=passwordConfirm,proto3" json:"password_confirm,omitempty"` // 确认密码最小长度5，最大长度10
	VerifyCode      string `protobuf:"bytes,4,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	Email           string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"` // 邮箱格式验证
	Phone           string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号长度11位
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignupByEmailRequest) Reset() {
	*x = SignupByEmailRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupByEmailRequest) ProtoMessage() {}

func (x *SignupByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupByEmailRequest.ProtoReflect.Descriptor instead.
func (*SignupByEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignupByEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupByEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupByEmailRequest) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

func (x *SignupByEmailRequest) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *SignupByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupByEmailRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// 邮箱注册响应
type SignupByEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *UserInfo              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupByEmailReply) Reset() {
	*x = SignupByEmailReply{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupByEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupByEmailReply) ProtoMessage() {}

func (x *SignupByEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupByEmailReply.ProtoReflect.Descriptor instead.
func (*SignupByEmailReply) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SignupByEmailReply) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignupByEmailReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 密码登录请求
type LoginByPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginId       string                 `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"` // 可以是用户名或邮箱
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	CaptchaAnswer string                 `protobuf:"bytes,4,opt,name=captcha_answer,json=captchaAnswer,proto3" json:"captcha_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByPasswordRequest) Reset() {
	*x = LoginByPasswordRequest{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPasswordRequest) ProtoMessage() {}

func (x *LoginByPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginByPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginByPasswordRequest) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *LoginByPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginByPasswordRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *LoginByPasswordRequest) GetCaptchaAnswer() string {
	if x != nil {
		return x.CaptchaAnswer
	}
	return ""
}

// 密码登录响应
type LoginByPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByPasswordReply) Reset() {
	*x = LoginByPasswordReply{}
	mi := &file_api_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPasswordReply) ProtoMessage() {}

func (x *LoginByPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPasswordReply.ProtoReflect.Descriptor instead.
func (*LoginByPasswordReply) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginByPasswordReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_auth_v1_auth_proto protoreflect.FileDescriptor

const file_api_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16api/auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"Z\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"\xfa\x01\n" +
	"\x14SignupByEmailRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\x04name\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18\n" +
	"R\bpassword\x124\n" +
	"\x10password_confirm\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18\n" +
	"R\x0fpasswordConfirm\x12)\n" +
	"\vverify_code\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x06R\n" +
	"verifyCode\x12\x1d\n" +
	"\x05email\x18\x05 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1e\n" +
	"\x05phone\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x05phone\"Q\n" +
	"\x12SignupByEmailReply\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.auth.v1.UserInfoR\x04data\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xa0\x01\n" +
	"\x16LoginByPasswordRequest\x12\x19\n" +
	"\blogin_id\x18\x01 \x01(\tR\aloginId\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18\n" +
	"R\bpassword\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tR\tcaptchaId\x12%\n" +
	"\x0ecaptcha_answer\x18\x04 \x01(\tR\rcaptchaAnswer\",\n" +
	"\x14LoginByPasswordReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xf8\x01\n" +
	"\x04Auth\x12s\n" +
	"\rSignupByEmail\x12\x1d.auth.v1.SignupByEmailRequest\x1a\x1b.auth.v1.SignupByEmailReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/auth/signup/using-email\x12{\n" +
	"\x0fLoginByPassword\x12\x1f.auth.v1.LoginByPasswordRequest\x1a\x1d.auth.v1.LoginByPasswordReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/auth/login/using-passwordB?\n" +
	"\x16dev.kratos.api.auth.v1B\vAuthProtoV1P\x01Z\x16krathub/api/auth/v1;v1b\x06proto3"

var (
	file_api_auth_v1_auth_proto_rawDescOnce sync.Once
	file_api_auth_v1_auth_proto_rawDescData []byte
)

func file_api_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_api_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_proto_rawDesc), len(file_api_auth_v1_auth_proto_rawDesc)))
	})
	return file_api_auth_v1_auth_proto_rawDescData
}

var file_api_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_auth_v1_auth_proto_goTypes = []any{
	(*UserInfo)(nil),               // 0: auth.v1.UserInfo
	(*SignupByEmailRequest)(nil),   // 1: auth.v1.SignupByEmailRequest
	(*SignupByEmailReply)(nil),     // 2: auth.v1.SignupByEmailReply
	(*LoginByPasswordRequest)(nil), // 3: auth.v1.LoginByPasswordRequest
	(*LoginByPasswordReply)(nil),   // 4: auth.v1.LoginByPasswordReply
}
var file_api_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.SignupByEmailReply.data:type_name -> auth.v1.UserInfo
	1, // 1: auth.v1.Auth.SignupByEmail:input_type -> auth.v1.SignupByEmailRequest
	3, // 2: auth.v1.Auth.LoginByPassword:input_type -> auth.v1.LoginByPasswordRequest
	2, // 3: auth.v1.Auth.SignupByEmail:output_type -> auth.v1.SignupByEmailReply
	4, // 4: auth.v1.Auth.LoginByPassword:output_type -> auth.v1.LoginByPasswordReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_proto_init() }
func file_api_auth_v1_auth_proto_init() {
	if File_api_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_proto_rawDesc), len(file_api_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_api_auth_v1_auth_proto = out.File
	file_api_auth_v1_auth_proto_goTypes = nil
	file_api_auth_v1_auth_proto_depIdxs = nil
}
