// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: auth/v1/hello.proto

package hellov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallHello_Hello_FullMethodName = "/krathub.hello.v1.CallHello/Hello"
)

// CallHelloClient is the client API for CallHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CallHello 定义一个简单的 Hello 服务
type CallHelloClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type callHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewCallHelloClient(cc grpc.ClientConnInterface) CallHelloClient {
	return &callHelloClient{cc}
}

func (c *callHelloClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, CallHello_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallHelloServer is the server API for CallHello service.
// All implementations must embed UnimplementedCallHelloServer
// for forward compatibility.
//
// CallHello 定义一个简单的 Hello 服务
type CallHelloServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCallHelloServer()
}

// UnimplementedCallHelloServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallHelloServer struct{}

func (UnimplementedCallHelloServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedCallHelloServer) mustEmbedUnimplementedCallHelloServer() {}
func (UnimplementedCallHelloServer) testEmbeddedByValue()                   {}

// UnsafeCallHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallHelloServer will
// result in compilation errors.
type UnsafeCallHelloServer interface {
	mustEmbedUnimplementedCallHelloServer()
}

func RegisterCallHelloServer(s grpc.ServiceRegistrar, srv CallHelloServer) {
	// If the following call pancis, it indicates UnimplementedCallHelloServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallHello_ServiceDesc, srv)
}

func _CallHello_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallHelloServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CallHello_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallHelloServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CallHello_ServiceDesc is the grpc.ServiceDesc for CallHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krathub.hello.v1.CallHello",
	HandlerType: (*CallHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _CallHello_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/hello.proto",
}
